# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            MO2k4
tagline:          'my blog'
description:      'Another developer blogging about technical stuff'
url:              
baseurl:          /

author:
  name:           'Martin Oehlert'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mo2k4/mo2k4.github.io
