# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Martin Oehlert
tagline:          'my blog'
description:      'Another developer blogging about technical stuff'

author:
  name:           'Martin Oehlert'

paginate:         5
emailme:          mo2k4_blog@gmx.de

gems:             [jekyll-paginate, jekyll-sitemap]

github:
  repo:           https://github.com/mo2k4/mo2k4.github.io

tags: